### ISSUE TITLE
Searching for Tearlaments cards returns the same card.

### ISSUE THREAD

**Issue by Linkyguy** [DawnbrandBots/bastion-bot#209]
As the tittle says, searching for Tearlament cards always return the same card: Tearlaments Scheiren. 
![image](https://user-images.githubusercontent.com/116177299/196701265-19c4baf4-0192-4d10-ad26-83ed3a3622f7.png)
![image](https://user-images.githubusercontent.com/116177299/196701307-22763939-43a9-47d1-923c-cd1344f962d9.png)
![image](https://user-images.githubusercontent.com/116177299/196701353-ca6488e4-7fd6-42c8-8221-33d3f78b4e67.png)

**Comment by Gideon9212** [comment]
The card your looking for has been renamed to Tearlaments Rulkallos.
https://yugipedia.com/wiki/Tearlaments_Rulkallos

**Comment by Gideon9212** [comment]
Most of <> search's look for exact names of cards. Quite sure the current search algorithm is meant to look for exact names but goes on best judgement when it doesn't match. It's why if you do <mst> you get mist worm instead of the mystical space typhoon. 

That said, that isn't a bug. At most, that's the current search algorithm standards at this time. A dev (because I'm not one, I just help provide support from time to time) can most likely confirm this when they are free. The .match command is most likely what your looking for in this type of case.

If you have any suggestions on improving the search algorithm or any other concerns on the search function, I suggest joining the discord for support as the issues for the github is for bugs, not complaints.

**Comment by kevinlul** [comment]
Hello, I don't see a bug here as you have described. As previously mentioned, the card name is now Rulkallos, and I can correctly resolve cards like Reinoheart and Havnis. If you expect "tearlaments rulk" to resolve to Rulkallos, that will be worked on as the new search algorithm has some quirks. If you expect "tearlaments kale" to resolve to Kaleido-Heart, that is also one of these quirks — the hyphen is a word boundary, so we have three tokens for this card name and "heart" is not receiving any matches. This is currently also causing searches with missing spaces (or any other word boundary) to not resolve as expected, which is why "kaleidoheart" doesn't resolve to Kaleido-Heart.

> My guess is that the search engine avoids archetypes names and goes to the secondary part of the name directly. 

This is not the case; rather, all your searches contain "tearlaments", so searching can find a card with that word in its name as the best name.

**Comment by kevinlul** [comment]
You can still file any issues you find on GitHub! We'll keep track of any unexpected mismatches for testing the search algorithm.
